name: buff
description: A buffer library for dart.
version: 1.0.0
repository: https://github.com/caijinglong/buff

environment:
  sdk: '>=2.12.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
